#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026  OtterStax


"""
Script for directly creating test data in running database instances.
Init SQL files are generated by fixtures/generate_data.py and mounted via docker-compose.
This script directly inserts data into running databases.

Data Model Overview:
====================
- MariaDB1 (mariadb1:3306/db1): campaigns table
    - campaign_id (PK), campaign_name, campaign_length, budget
    
- MariaDB2 (mariadb2:3306/db2): impressions table  
    - impression_id (PK), campaign_id (FK), days_since_start, clicks, conversions, revenue
    
- PostgreSQL (postgres1:5432/pgdb): products table
    - product_id (PK, SERIAL), campaign_id (FK), product_name, price, category
    
- ClickHouse (clickhouse1:9000/chdb): orders table
    - order_id, campaign_id (FK), product_id (FK), customer_name, order_date, quantity, total_amount

Data Correlation:
=================
- All databases share the same campaign_id values (1-50) for cross-database JOINs
- ClickHouse orders.product_id references actual PostgreSQL products.product_id
- Each campaign has:
  - 100 impressions (one per day of campaign)
  - 2-5 products
  - 10-50 orders
"""
import os
import random
from faker import Faker

# Initialize Faker with English locale
fake = Faker('en_US')

# Generation parameters
NUM_CAMPAIGNS = 50
IMPRESSIONS_PER_CAMPAIGN = 100
ORDERS_PER_CAMPAIGN = 30

def create_test_data():
    print("🔧 Starting test data creation...")

    # Test database connections first
    print("\n🔍 Testing database connections...")

    # Test MariaDB1 connection
    print("  Testing MariaDB1 connection...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb1",
            port=3306,
            user="user1",
            password="password1",
            database="db1"
        )
        print("  ✅ MariaDB1 connection successful")
        conn.close()
    except Exception as e:
        print(f"  ❌ MariaDB1 connection failed: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Test MariaDB2 connection
    print("  Testing MariaDB2 connection...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb2",
            port=3306,
            user="user2",
            password="password2",
            database="db2"
        )
        print("  ✅ MariaDB2 connection successful")
        conn.close()
    except Exception as e:
        print(f"  ❌ MariaDB2 connection failed: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Test PostgreSQL connection
    print("  Testing PostgreSQL connection...")
    try:
        import psycopg2
        conn = psycopg2.connect(
            host="postgres1",
            port=5432,
            user="pguser",
            password="pgpassword",
            database="pgdb"
        )
        print("  ✅ PostgreSQL connection successful")
        conn.close()
    except Exception as e:
        print(f"  ❌ PostgreSQL connection failed: {e}")
        import traceback
        traceback.print_exc()
        # Don't raise - PostgreSQL is optional for now

    # Test ClickHouse connection
    print("  Testing ClickHouse connection...")
    try:
        import clickhouse_driver
        # First test basic connection
        conn_init = clickhouse_driver.Client(
            host="clickhouse1",
            port=9000,
            user="chuser",
            password="chpassword"
        )
        result = conn_init.execute("SELECT 1")
        
        # Check if chdb database exists
        conn_init.execute("CREATE DATABASE IF NOT EXISTS chdb")
        
        conn = clickhouse_driver.Client(
            host="clickhouse1",
            port=9000,
            user="chuser",
            password="chpassword",
            database="chdb"
        )
        result = conn.execute("SELECT COUNT(*) FROM system.tables WHERE database = 'chdb'")
        print(f"  ✅ ClickHouse connection successful (chdb database has {result[0][0]} tables)")
    except Exception as e:
        print(f"  ❌ ClickHouse connection failed: {e}")
        import traceback
        traceback.print_exc()
        # Don't raise - ClickHouse is optional for now

    # Generate campaign data for use across all databases
    campaigns_data = []
    print(f"🔧 Generating {NUM_CAMPAIGNS} campaigns...")
    for i in range(1, NUM_CAMPAIGNS + 1):
        campaign_length = random.randint(30, 90)
        budget = round(random.uniform(5000, 100000), 2)
        campaign_name = f"Campaign {fake.word().capitalize()} {fake.word().capitalize()}"
        campaigns_data.append({
            'id': i,
            'name': campaign_name,
            'campaign_length': campaign_length,
            'budget': budget
        })

    # Directly create MySQL tables in mariadb1
    print("🔧 Creating MySQL campaigns table in mariadb1...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb1",
            port=3306,
            user="user1",
            password="password1",
            database="db1"
        )
        cur = conn.cursor()

        # Create campaigns table
        cur.execute("DROP TABLE IF EXISTS campaigns")
        cur.execute("""
            CREATE TABLE campaigns (
                campaign_id INT PRIMARY KEY,
                campaign_name VARCHAR(255) NOT NULL,
                campaign_length INT NOT NULL,
                budget FLOAT NOT NULL
            )
        """)

        # Insert data
        for campaign in campaigns_data:
            cur.execute(
                "INSERT INTO campaigns (campaign_id, campaign_name, campaign_length, budget) VALUES (%s, %s, %s, %s)",
                (campaign['id'], campaign['name'], campaign['campaign_length'], campaign['budget'])
            )
        conn.commit()

        # Verify table was created
        cur.execute("SELECT COUNT(*) FROM campaigns")
        count = cur.fetchone()[0]
        print(f"✅ MySQL campaigns table created with {count} rows")

        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error creating MySQL campaigns table: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Directly create MySQL impressions table in mariadb2
    print("🔧 Creating MySQL impressions table in mariadb2...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb2",
            port=3306,
            user="user2",
            password="password2",
            database="db2"
        )
        cur = conn.cursor()

        # Create impressions table
        cur.execute("DROP TABLE IF EXISTS impressions")
        cur.execute("""
            CREATE TABLE impressions (
                impression_id INT PRIMARY KEY,
                campaign_id INT NOT NULL,
                days_since_start INT NOT NULL,
                clicks INT NOT NULL,
                conversions INT NOT NULL,
                revenue FLOAT NOT NULL
            )
        """)

        # Insert data
        imp_id = 1
        for campaign in campaigns_data:
            current_length = 0
            for day in range(IMPRESSIONS_PER_CAMPAIGN):
                if current_length > campaign['campaign_length']:
                    break
                clicks = random.randint(50, 500)
                conversion_rate = random.uniform(0.01, 0.1)
                conversions = int(clicks * conversion_rate)
                revenue_per_conversion = random.uniform(1, 5)
                revenue = round(conversions * revenue_per_conversion, 2)
                cur.execute(
                    "INSERT INTO impressions (impression_id, campaign_id, days_since_start, clicks, conversions, revenue) VALUES (%s, %s, %s, %s, %s, %s)",
                    (imp_id, campaign['id'], current_length, clicks, conversions, revenue)
                )
                imp_id += 1
                current_length += 1
        conn.commit()

        # Verify table was created
        cur.execute("SELECT COUNT(*) FROM impressions")
        count = cur.fetchone()[0]
        print(f"✅ MySQL impressions table created with {count} rows")

        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error creating MySQL impressions table: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Create PostgreSQL products table
    print("🔧 Creating PostgreSQL products table...")
    try:
        import psycopg2
        conn = psycopg2.connect(
            host="postgres1",
            port=5432,
            user="pguser",
            password="pgpassword",
            database="pgdb"
        )
        conn.autocommit = True
        cur = conn.cursor()

        # Create the table
        create_table_sql = """
        DROP TABLE IF EXISTS products;
        CREATE TABLE products (
            product_id SERIAL PRIMARY KEY,
            campaign_id INT NOT NULL,
            product_name VARCHAR(255) NOT NULL,
            price FLOAT NOT NULL,
            category VARCHAR(100) NOT NULL
        );
        """
        print("  Creating products table...")
        cur.execute(create_table_sql)
        print("  Products table created.")

        # Insert data
        print("  Inserting product data...")
        insert_count = 0
        product_id = 1
        categories = ['Electronics', 'Clothing', 'Food', 'Home', 'Sports', 'Books', 'Toys', 'Beauty']
        for campaign in campaigns_data:
            num_products = random.randint(2, 5)
            for _ in range(num_products):
                product_name = f"{fake.word().capitalize()} {fake.word().capitalize()}"
                price = round(random.uniform(9.99, 499.99), 2)
                category = random.choice(categories)
                cur.execute(
                    "INSERT INTO products (campaign_id, product_name, price, category) VALUES (%s, %s, %s, %s)",
                    (campaign['id'], product_name, price, category)
                )
                insert_count += 1
                product_id += 1

        cur.close()
        conn.close()
        print(f"✅ PostgreSQL products table created with {insert_count} rows")
    except Exception as e:
        print(f"⚠️  Could not create PostgreSQL table: {e}")
        import traceback
        traceback.print_exc()
        # Don't raise - PostgreSQL is optional for now

    # Create ClickHouse orders table
    print("🔧 Creating ClickHouse orders table...")
    try:
        import clickhouse_driver
        # First ensure database exists
        conn_init = clickhouse_driver.Client(
            host="clickhouse1",
            port=9000,
            user="chuser",
            password="chpassword"
        )
        conn_init.execute("CREATE DATABASE IF NOT EXISTS chdb")
        
        conn = clickhouse_driver.Client(
            host="clickhouse1",
            port=9000,
            user="chuser",
            password="chpassword",
            database="chdb"
        )

        # Create the table
        print("  Creating orders table...")
        conn.execute("DROP TABLE IF EXISTS orders")
        conn.execute("""
            CREATE TABLE orders (
                order_id Int64,
                campaign_id Int32,
                product_id Int32,
                customer_name String,
                order_date DateTime,
                quantity Int32,
                total_amount Float64
            ) ENGINE = MergeTree()
            ORDER BY (campaign_id, order_date)
        """)
        print("  Orders table created.")

        # First, fetch actual product IDs from PostgreSQL to ensure correlation
        product_ids = []
        try:
            import psycopg2
            pg_conn = psycopg2.connect(
                host="postgres1",
                port=5432,
                user="pguser",
                password="pgpassword",
                database="pgdb"
            )
            pg_cur = pg_conn.cursor()
            pg_cur.execute("SELECT product_id FROM products")
            product_ids = [row[0] for row in pg_cur.fetchall()]
            pg_cur.close()
            pg_conn.close()
            print(f"  Fetched {len(product_ids)} product IDs from PostgreSQL for correlation")
        except Exception as e:
            print(f"  ⚠️  Could not fetch product IDs from PostgreSQL: {e}")
            # Fallback: generate sequential IDs matching expected product count
            product_ids = list(range(1, len(campaigns_data) * 3 + 1))  # ~3 products per campaign avg

        # Insert data — collect all rows, then one batch insert
        # (clickhouse_driver batch insert: query ends with VALUES, no placeholders)
        print("  Inserting order data...")
        rows_to_insert = []
        order_id = 1
        for campaign in campaigns_data:
            for _ in range(ORDERS_PER_CAMPAIGN):
                customer_name = f"{fake.first_name()} {fake.last_name()}"
                order_date = fake.date_time_between(start_date='-1y', end_date='now')
                quantity = random.randint(1, 10)
                total_amount = round(quantity * random.uniform(19.99, 999.99), 2)
                product_id_link = random.choice(product_ids) if product_ids else 1
                rows_to_insert.append((
                    order_id, campaign['id'], product_id_link,
                    customer_name, order_date, quantity, total_amount
                ))
                order_id += 1

        conn.execute(
            "INSERT INTO orders"
            " (order_id, campaign_id, product_id, customer_name, order_date, quantity, total_amount)"
            " VALUES",
            rows_to_insert
        )
        print(f"✅ ClickHouse orders table created with {len(rows_to_insert)} rows")
    except Exception as e:
        print(f"⚠️  Could not create ClickHouse table: {e}")
        import traceback
        traceback.print_exc()
        # Don't raise - ClickHouse is optional for now

    print("\n" + "="*60)
    print("✅ Test data creation completed successfully!")
    print("="*60)

if __name__ == "__main__":
    create_test_data()
