#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026  OtterStax


"""
Script for directly creating test data in running database instances.
Init SQL files are generated by fixtures/generate_data.py and mounted via docker-compose.
This script directly inserts data into running databases.
"""
import os
import random
from faker import Faker

# Initialize Faker with English locale
fake = Faker('en_US')

# Generation parameters
NUM_CAMPAIGNS = 50
IMPRESSIONS_PER_CAMPAIGN = 100

def create_test_data():
    print("🔧 Starting test data creation...")

    # Test database connections first
    print("\n🔍 Testing database connections...")

    # Test MariaDB1 connection
    print("  Testing MariaDB1 connection...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb1",
            port=3306,
            user="user1",
            password="password1",
            database="db1"
        )
        print("  ✅ MariaDB1 connection successful")
        conn.close()
    except Exception as e:
        print(f"  ❌ MariaDB1 connection failed: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Test MariaDB2 connection
    print("  Testing MariaDB2 connection...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb2",
            port=3306,
            user="user2",
            password="password2",
            database="db2"
        )
        print("  ✅ MariaDB2 connection successful")
        conn.close()
    except Exception as e:
        print(f"  ❌ MariaDB2 connection failed: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Test PostgreSQL connection
    print("  Testing PostgreSQL connection...")
    try:
        import psycopg2
        conn = psycopg2.connect(
            host="postgres1",
            port=5432,
            user="pguser",
            password="pgpassword",
            database="pgdb"
        )
        print("  ✅ PostgreSQL connection successful")
        conn.close()
    except Exception as e:
        print(f"  ❌ PostgreSQL connection failed: {e}")
        import traceback
        traceback.print_exc()
        # Don't raise - PostgreSQL is optional for now

    # Generate campaign data for use across all databases
    campaigns_data = []
    print(f"🔧 Generating {NUM_CAMPAIGNS} campaigns...")
    for i in range(1, NUM_CAMPAIGNS + 1):
        campaign_length = random.randint(30, 90)
        budget = round(random.uniform(5000, 100000), 2)
        campaign_name = f"Campaign {fake.word().capitalize()} {fake.word().capitalize()}"
        campaigns_data.append({
            'id': i,
            'name': campaign_name,
            'campaign_length': campaign_length,
            'budget': budget
        })

    # Directly create MySQL tables in mariadb1
    print("🔧 Creating MySQL campaigns table in mariadb1...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb1",
            port=3306,
            user="user1",
            password="password1",
            database="db1"
        )
        cur = conn.cursor()

        # Create campaigns table
        cur.execute("DROP TABLE IF EXISTS campaigns")
        cur.execute("""
            CREATE TABLE campaigns (
                campaign_id INT PRIMARY KEY,
                campaign_name VARCHAR(255) NOT NULL,
                campaign_length INT NOT NULL,
                budget FLOAT NOT NULL
            )
        """)

        # Insert data
        for campaign in campaigns_data:
            cur.execute(
                "INSERT INTO campaigns (campaign_id, campaign_name, campaign_length, budget) VALUES (%s, %s, %s, %s)",
                (campaign['id'], campaign['name'], campaign['campaign_length'], campaign['budget'])
            )
        conn.commit()

        # Verify table was created
        cur.execute("SELECT COUNT(*) FROM campaigns")
        count = cur.fetchone()[0]
        print(f"✅ MySQL campaigns table created with {count} rows")

        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error creating MySQL campaigns table: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Directly create MySQL impressions table in mariadb2
    print("🔧 Creating MySQL impressions table in mariadb2...")
    try:
        import pymysql
        conn = pymysql.connect(
            host="mariadb2",
            port=3306,
            user="user2",
            password="password2",
            database="db2"
        )
        cur = conn.cursor()

        # Create impressions table
        cur.execute("DROP TABLE IF EXISTS impressions")
        cur.execute("""
            CREATE TABLE impressions (
                impression_id INT PRIMARY KEY,
                campaign_id INT NOT NULL,
                days_since_start INT NOT NULL,
                clicks INT NOT NULL,
                conversions INT NOT NULL,
                revenue FLOAT NOT NULL
            )
        """)

        # Insert data
        imp_id = 1
        for campaign in campaigns_data:
            current_length = 0
            for day in range(IMPRESSIONS_PER_CAMPAIGN):
                if current_length > campaign['campaign_length']:
                    break
                clicks = random.randint(50, 500)
                conversion_rate = random.uniform(0.01, 0.1)
                conversions = int(clicks * conversion_rate)
                revenue_per_conversion = random.uniform(1, 5)
                revenue = round(conversions * revenue_per_conversion, 2)
                cur.execute(
                    "INSERT INTO impressions (impression_id, campaign_id, days_since_start, clicks, conversions, revenue) VALUES (%s, %s, %s, %s, %s, %s)",
                    (imp_id, campaign['id'], current_length, clicks, conversions, revenue)
                )
                imp_id += 1
                current_length += 1
        conn.commit()

        # Verify table was created
        cur.execute("SELECT COUNT(*) FROM impressions")
        count = cur.fetchone()[0]
        print(f"✅ MySQL impressions table created with {count} rows")

        cur.close()
        conn.close()
    except Exception as e:
        print(f"❌ Error creating MySQL impressions table: {e}")
        import traceback
        traceback.print_exc()
        raise

    # Create PostgreSQL products table
    print("🔧 Creating PostgreSQL products table...")
    try:
        import psycopg2
        conn = psycopg2.connect(
            host="postgres1",
            port=5432,
            user="pguser",
            password="pgpassword",
            database="pgdb"
        )
        conn.autocommit = True
        cur = conn.cursor()

        # Create the table
        create_table_sql = """
        DROP TABLE IF EXISTS products;
        CREATE TABLE products (
            product_id SERIAL PRIMARY KEY,
            campaign_id INT NOT NULL,
            product_name VARCHAR(255) NOT NULL,
            price FLOAT NOT NULL,
            category VARCHAR(100) NOT NULL
        );
        """
        print("  Creating products table...")
        cur.execute(create_table_sql)
        print("  Products table created.")

        # Insert data
        print("  Inserting product data...")
        insert_count = 0
        product_id = 1
        categories = ['Electronics', 'Clothing', 'Food', 'Home', 'Sports', 'Books', 'Toys', 'Beauty']
        for campaign in campaigns_data:
            num_products = random.randint(2, 5)
            for _ in range(num_products):
                product_name = f"{fake.word().capitalize()} {fake.word().capitalize()}"
                price = round(random.uniform(9.99, 499.99), 2)
                category = random.choice(categories)
                cur.execute(
                    "INSERT INTO products (campaign_id, product_name, price, category) VALUES (%s, %s, %s, %s)",
                    (campaign['id'], product_name, price, category)
                )
                insert_count += 1
                product_id += 1

        cur.close()
        conn.close()
        print(f"✅ PostgreSQL products table created with {insert_count} rows")
    except Exception as e:
        print(f"⚠️  Could not create PostgreSQL table: {e}")
        import traceback
        traceback.print_exc()
        # Don't raise - PostgreSQL is optional for now

    print("\n" + "="*60)
    print("✅ Test data creation completed successfully!")
    print("="*60)

if __name__ == "__main__":
    create_test_data()
