# SPDX-License-Identifier: Apache-2.0
# Copyright 2025-2026  OtterStax

"""Shared helpers for the MySQL-wire external-table integration tests.

Exercises the s3/file grammar-extension routing end-to-end over the MySQL wire:

    CREATE EXTERNAL TABLE <db>.<table> WITH (location=..., format=...)
    COPY (<select>) TO '<location>' WITH (format=...)

Two richer, joinable fixtures (generated by
tests/minio/fixtures/generate_external_fixtures.py, smaller-scale siblings of
tests/create_test_data.py) are used so loads, schemas, aggregates and JOINs can
all be asserted:

  regions.parquet   200 rows   (region_id, campaign_id, region_name, country, population, ad_spend)
  web_events.csv   5000 rows   (event_id, campaign_id, product_id, event_type, session_seconds, value)

Both correlate on campaign_id (1..50), so the two external tables JOIN with each
other (and would JOIN the MariaDB/PG/CH backends, which share campaign_id).

`source="file"` reads local paths mounted into the otterstax container
(``/fixtures/...``); `source="s3"` reads ``s3://<bucket>/...`` after registering
MinIO credentials through the HTTP API.
"""

import argparse
import sys

import mysql.connector

import config

# Must mirror tests/minio/fixtures/generate_external_fixtures.py.
NUM_CAMPAIGNS = 50
REGIONS_PER_CAMPAIGN = 4
EVENTS_PER_CAMPAIGN = 100

DATASETS = [
    {
        "name": "regions",
        "file": "regions.parquet",
        "fmt": "parquet",
        "columns": ["region_id", "campaign_id", "region_name", "country", "population", "ad_spend"],
        "rows": NUM_CAMPAIGNS * REGIONS_PER_CAMPAIGN,      # 200
        "per_campaign": REGIONS_PER_CAMPAIGN,
    },
    {
        "name": "web_events",
        "file": "web_events.csv",
        "fmt": "csv",
        "columns": ["event_id", "campaign_id", "product_id", "event_type", "session_seconds", "value"],
        "rows": NUM_CAMPAIGNS * EVENTS_PER_CAMPAIGN,       # 5000
        "per_campaign": EVENTS_PER_CAMPAIGN,
    },
]

# regions(4/campaign) ⋈ web_events(100/campaign) on campaign_id over 50 campaigns.
JOIN_ROWS = NUM_CAMPAIGNS * REGIONS_PER_CAMPAIGN * EVENTS_PER_CAMPAIGN  # 20000

# In-container view of the seeded MinIO + fixture mount (see compose.test.yml).
S3_ALIAS = "miniotest"
S3_BUCKET = "test-bucket"
S3_ENDPOINT = "minio:9000"
S3_ACCESS_KEY = "minioadmin"
S3_SECRET_KEY = "minioadmin"
S3_REGION = "us-east-1"
FILE_FIXTURE_DIR = "/fixtures"


class ExternalTableTester:
    def __init__(self, source, local=False):
        assert source in ("file", "s3"), source
        self.source = source
        self.host = config.get_host(local)
        self.conn_cfg = {
            "host": self.host,
            "port": config.MYSQL_PORT,
            "user": "testuser",
            "password": "testpass",
        }
        self._created = []  # (db, table) pairs to drop on cleanup

    # ── connection ───────────────────────────────────────────────────────────
    def connect(self):
        return mysql.connector.connect(**self.conn_cfg)

    # ── s3 credential registration ───────────────────────────────────────────
    def ensure_credentials(self):
        # No-op. There is no runtime credential API anymore — the '{alias}' s3
        # alias is registered from the server's connection config file at startup
        # (tests/scripts/config.yaml, baked into the otterstax image). Kept
        # as a no-op so existing test call sites need no change.
        if self.source != "s3":
            return
        print(f"Using pre-registered s3 alias '{S3_ALIAS}' (from startup connection config)")

    # ── SQL fragment builders ────────────────────────────────────────────────
    def _source_location(self, filename):
        if self.source == "s3":
            return f"s3://{S3_BUCKET}/{filename}"
        return f"{FILE_FIXTURE_DIR}/{filename}"

    def _copy_target(self, name, fmt):
        filename = f"{name}.{fmt}"
        if self.source == "s3":
            return f"s3://{S3_BUCKET}/exported/{filename}"
        return f"/tmp/otterstax_copy_{filename}"

    def _create_with(self, location, fmt):
        # CREATE carries the location in WITH(...).
        alias = f"s3_alias = '{S3_ALIAS}', " if self.source == "s3" else ""
        return f"WITH ({alias}location = '{location}', format = '{fmt}')"

    def _copy_with(self, fmt):
        # COPY carries the location as the TO target; WITH holds only s3_alias/format.
        alias = f"s3_alias = '{S3_ALIAS}', " if self.source == "s3" else ""
        return f"WITH ({alias}format = '{fmt}')"

    # ── DDL helpers ──────────────────────────────────────────────────────────
    def create_external(self, cur, db, table, filename, fmt):
        location = self._source_location(filename)
        cur.execute(f"CREATE EXTERNAL TABLE {db}.{table} {self._create_with(location, fmt)}")
        self._created.append((db, table))

    def create_external_from(self, cur, db, table, location, fmt):
        cur.execute(f"CREATE EXTERNAL TABLE {db}.{table} {self._create_with(location, fmt)}")
        self._created.append((db, table))

    def copy_to(self, cur, db, table, name, fmt):
        target = self._copy_target(name, fmt)
        cur.execute(f"COPY (SELECT * FROM {db}.{table}) TO '{target}' {self._copy_with(fmt)}")
        return target

    def cleanup(self):
        try:
            conn = self.connect()
            cur = conn.cursor()
            for db, table in self._created:
                try:
                    cur.execute(f"drop table {db}.{table}")
                except Exception:  # noqa: BLE001 — best-effort teardown
                    pass
            conn.close()
        except Exception:  # noqa: BLE001
            pass


def _scalar(cur, sql):
    cur.execute(sql)
    return cur.fetchall()[0][0]


def run_data_test(source, local=False):
    """Load both datasets, verify row counts / aggregates, COPY each back out and
    round-trip it, then JOIN the two external tables on the shared campaign_id."""
    tester = ExternalTableTester(source, local=local)
    tester.ensure_credentials()
    conn = tester.connect()
    db = f"extdata_{source}"
    try:
        cur = conn.cursor()
        for ds in DATASETS:
            tester.create_external(cur, db, ds["name"], ds["file"], ds["fmt"])

            count = int(_scalar(cur, f"select count(*) from {db}.{ds['name']}"))
            if count != ds["rows"]:
                raise AssertionError(f"[{source}/{ds['name']}] count {count} != {ds['rows']}")

            cur.execute(f"select min(campaign_id), max(campaign_id) from {db}.{ds['name']}")
            lo, hi = cur.fetchall()[0]
            if int(lo) != 1 or int(hi) != NUM_CAMPAIGNS:
                raise AssertionError(f"[{source}/{ds['name']}] campaign_id range [{lo},{hi}] != [1,{NUM_CAMPAIGNS}]")

            # Deterministic per-campaign counts: GROUP BY exercises an aggregate
            # over the loaded external data (each campaign has a fixed row count).
            cur.execute(f"select campaign_id, count(*) from {db}.{ds['name']} group by campaign_id")
            grp = cur.fetchall()
            if len(grp) != NUM_CAMPAIGNS:
                raise AssertionError(f"[{source}/{ds['name']}] {len(grp)} campaigns != {NUM_CAMPAIGNS}")
            if any(int(c) != ds["per_campaign"] for _, c in grp):
                raise AssertionError(f"[{source}/{ds['name']}] non-uniform per-campaign count: {grp[:5]}...")

            # COPY the result out, then load it back through a fresh external table.
            target = tester.copy_to(cur, db, ds["name"], ds["name"], ds["fmt"])
            rt = f"{ds['name']}_rt"
            tester.create_external_from(cur, db, rt, target, ds["fmt"])
            rt_count = int(_scalar(cur, f"select count(*) from {db}.{rt}"))
            if rt_count != ds["rows"]:
                raise AssertionError(f"[{source}/{ds['name']}] COPY round-trip count {rt_count} != {ds['rows']}")

            print(f"  ✓ {source}/{ds['name']} ({ds['fmt']}): {count} rows, {len(grp)} campaigns, COPY round-trip OK")

        # JOIN the two external tables on the shared campaign_id key.
        join_count = int(_scalar(
            cur,
            f"select count(*) from {db}.regions r "
            f"join {db}.web_events e on r.campaign_id = e.campaign_id"))
        if join_count != JOIN_ROWS:
            raise AssertionError(f"[{source}] regions⋈web_events count {join_count} != {JOIN_ROWS}")
        print(f"  ✓ {source}: regions ⋈ web_events on campaign_id = {join_count} rows")
    finally:
        conn.close()
        tester.cleanup()


def run_schema_test(source, local=False):
    """Load both datasets and verify each external table's column schema (names +
    count) is exposed correctly over the wire."""
    tester = ExternalTableTester(source, local=local)
    tester.ensure_credentials()
    conn = tester.connect()
    db = f"extschema_{source}"
    try:
        cur = conn.cursor()
        for ds in DATASETS:
            tester.create_external(cur, db, ds["name"], ds["file"], ds["fmt"])

            cur.execute(f"select * from {db}.{ds['name']}")
            rows = cur.fetchall()  # drain so the connection stays reusable
            columns = [d[0] for d in cur.description]
            if columns != ds["columns"]:
                raise AssertionError(f"[{source}/{ds['name']}] columns {columns} != {ds['columns']}")
            if len(rows) != ds["rows"]:
                raise AssertionError(f"[{source}/{ds['name']}] expected {ds['rows']} rows, got {len(rows)}")
            print(f"  ✓ {source}/{ds['name']} ({ds['fmt']}): schema columns={columns}")
    finally:
        conn.close()
        tester.cleanup()


def main(kind, source):
    """CLI entry point shared by the four thin test files."""
    parser = argparse.ArgumentParser(description=f"External-table {kind} test ({source}) over the MySQL wire")
    parser.add_argument("--local", action="store_true", help="Use 0.0.0.0 instead of test-otterstax")
    args = parser.parse_args()

    label = f"{kind.upper()} — MySQL wire / {source} external tables"
    runner = run_schema_test if kind == "schema" else run_data_test
    try:
        runner(source, local=args.local)
        print("\n" + "=" * 70)
        print(f"\033[92m✅ ALL TESTS PASSED - {label}\033[0m")
        print("=" * 70)
        return 0
    except Exception as exc:  # noqa: BLE001
        print("\n" + "=" * 70)
        print(f"\033[91m❌ TEST FAILED - {label}\033[0m")
        print(f"\033[91m{exc}\033[0m")
        print("=" * 70)
        return 1
    finally:
        print("Test completed.")
