// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026  OtterStax

#pragma once

#include <actor-zeta.hpp>
#include <components/log/log.hpp>

#include "catalog/discovery.hpp"
#include "connectors/postgresql/manager.hpp"
#include "otterbrix/parser/parser.hpp"
#include "otterbrix/schema/schema_utils.hpp"
#include "otterbrix/translators/input/pg_to_chunk.hpp"
#include "utility/session.hpp"
#include "utility/tracy_profiler.hpp"

#include <core/result_wrapper.hpp>

#include <memory_resource>
#include <mutex>
#include <string>
#include <unordered_map>

namespace db {
    // PostgressManager ONLY fetches data from PostgreSQL, NO JOIN operations
    class PostgressManager final : public actor_zeta::actor::actor_mixin<PostgressManager> {
    public:
        using is_cooperative_actor_type = void; // Required by actor_zeta::send() concept
        template<typename T>
        using unique_future = actor_zeta::unique_future<T>;

        PostgressManager(std::pmr::memory_resource* res, pg::ConnectorManager* connector_manager);

        std::pmr::memory_resource* resource() const noexcept { return resource_; }

        /// handler coroutine — ONLY fetches data, does NOT perform JOIN
        actor_zeta::unique_future<core::result_wrapper_t<ParsedQueryDataPtr>> execute(session_hash_t id,
                                                                                      ParsedQueryDataPtr data);

        // Schema discovery for the catalog: `scope` carries the database and
        // schema the probes run against (a missing schema is missing_field);
        // empty `scope.collection` → every base table of that schema, non-empty
        // → that single table. Refreshes the connection's ENUM oid map first —
        // a failed metadata query fails the discovery, so a table is never
        // registered with degraded column types. Every connector future is
        // consumed here, on this actor, so the connector manager has one driver.
        actor_zeta::unique_future<core::result_wrapper_t<catalog_ext::discovered_tables_t>>
        discover(qualified_name_t scope);

        // The prepared schema of the statement's PostgreSQL slots, answered by
        // the backend. For every schema_node_t stub — the catalog's, made of an
        // aggregate slot, and the parser's, carrying the raw text of a lifted-out
        // sub-query — the statement execute would run for it is generated by the
        // same call, wrapped as a LIMIT-0 probe (prepare_probe.hpp) and run:
        // PostgreSQL answers the RowDescription of the wrapped statement, and
        // ExecLimit reports the empty result without pulling a row from the
        // subplan. The result goes through tsl::pg_to_struct under the
        // connection's ENUM oids, exactly as execute's tuples go through
        // pg_to_chunk, so the prepared column types are the executed chunk's by
        // construction — a function aliased as a base column
        // (`length(name) AS name`) has no type on the plan at all, and a raw-SQL
        // stub has no schema on the plan either. Such a stub's schema is filled
        // in place, so the text and qualifiers execute generates from survive. A
        // parameterized statement cannot be described before Bind — the binder
        // holds every parameter, literals included, until finalize, so no SQL
        // exists to probe with — and is unimplemented_yet, never a plan-derived
        // guess. A probe the backend refuses is the connector's error, code kept;
        // an answer without columns is schema_error; a uid whose discovery left
        // no ENUM metadata is do_not_exists, as in execute. Nothing is cached:
        // every prepare asks the backend. Sent by the Worker after
        // CatalogManager::get_catalog_schema classified the statement; a Mixed
        // statement's non-PostgreSQL slots are skipped by their
        // node_backend_types entry.
        actor_zeta::unique_future<core::result_wrapper_t<ParsedQueryDataPtr>> describe(session_hash_t id,
                                                                                       ParsedQueryDataPtr data);

        using dispatch_traits = actor_zeta::dispatch_traits<&PostgressManager::execute,
                                                            &PostgressManager::discover,
                                                            &PostgressManager::describe>;

        actor_zeta::behavior_t behavior(actor_zeta::mailbox::message* msg);

        std::pair<bool, actor_zeta::detail::enqueue_result> enqueue_impl(actor_zeta::mailbox::message_ptr msg);

    private:
        std::pmr::memory_resource* resource_;
        // Non-owning: ComponentManager owns it and outlives this actor. This
        // actor is its only driver after startup (execute and discover both run
        // here, serialised by mutex_).
        pg::ConnectorManager* connector_manager_;
        log_t log_;
        OTX_LOCKABLE_N(std::mutex, mutex_, "PostgressManager::mutex");
        actor_zeta::behavior_t current_behavior_;
        // ENUM type oid → labels per connection uid, the metadata pg_to_chunk
        // needs to decode enum columns. Actor-confined: assigned by discover
        // from the value the io-thread query handed back, read by execute —
        // both under mutex_. Every uid that went through discovery has an
        // entry (possibly empty); execute treats a missing one as an error.
        std::pmr::unordered_map<std::pmr::string, tsl::pg_enum_oid_map> enums_;

        // Runs the pg_enum query on the connection and returns the decoded map
        // as a value; nothing is cached before the outcome is known.
        core::result_wrapper_t<tsl::pg_enum_oid_map> fetch_enum_types(const std::string& uuid);

        // The statement one slot sends to PostgreSQL — shared by execute (which
        // runs it) and describe (which probes its header), so both see one text.
        core::result_wrapper_t<std::string>
        generate_slot_statement(const components::logical_plan::node_ptr& node,
                                const otterstax::names::resolved_target_t& target,
                                const std::pmr::vector<external_entry_t>& batch,
                                const components::logical_plan::storage_parameters* parameters);
    };
} // namespace db
