// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026  OtterStax

#pragma once

#include <actor-zeta.hpp>
#include <components/log/log.hpp>

#include "catalog/discovery.hpp"
#include "connectors/mysql/manager.hpp"
#include "otterbrix/parser/parser.hpp"
#include "otterbrix/schema/schema_utils.hpp"
#include "utility/session.hpp"
#include "utility/tracy_profiler.hpp"

#include <core/result_wrapper.hpp>

#include <memory_resource>
#include <mutex>
#include <string>

namespace db {
    class MySQLManager final : public actor_zeta::actor::actor_mixin<MySQLManager> {
    public:
        using is_cooperative_actor_type = void; // Required by actor_zeta::send() concept
        template<typename T>
        using unique_future = actor_zeta::unique_future<T>;

        MySQLManager(std::pmr::memory_resource* res, mysql::ConnectorManager* connector_manager);

        std::pmr::memory_resource* resource() const noexcept { return resource_; }

        /// handler coroutine
        actor_zeta::unique_future<core::result_wrapper_t<ParsedQueryDataPtr>> execute(session_hash_t id,
                                                                                      ParsedQueryDataPtr data);

        // Schema discovery for the catalog: empty `scope.collection` → every
        // base table of `scope.database` (information_schema listing, then one
        // probe per table); non-empty → that single table. Every connector
        // future is consumed here, on this actor, so the connector manager has
        // one driver. A per-table probe failure fails the whole discovery.
        actor_zeta::unique_future<core::result_wrapper_t<catalog_ext::discovered_tables_t>>
        discover(qualified_name_t scope);

        // The prepared schema of the statement's MySQL slots, answered by the
        // backend. For every schema_node_t stub — the catalog's, made of an
        // aggregate slot, and the parser's, carrying the raw text of a lifted-out
        // sub-query — the statement execute would run for it is generated by the
        // same call, wrapped as a LIMIT-0 probe (prepare_probe.hpp) and run:
        // MySQL sends a SELECT's column definitions ahead of its rows, so the
        // answer carries the result's columns and their wire types, and the
        // connection reads them in metadata_mode::full. The answer goes through
        // tsl::mysql_to_chunk — the function that types execute's rows, which is
        // the one table tsl::mysql_to_struct answers discovery from — so the
        // prepared column types are the executed chunk's by construction, and a
        // column type the translator cannot represent is the same
        // conversion_failure execute answers for it.
        // A raw-SQL stub's schema is filled in place, so the text and qualifiers
        // execute generates from survive. A parameterized statement cannot be
        // described before Bind — the binder holds every parameter, literals
        // included, until finalize, so no SQL exists to probe with — and is
        // unimplemented_yet, never a plan-derived guess. A probe the backend
        // refuses is the connector's error, code kept; an answer without column
        // metadata is schema_error. Nothing is cached: every prepare asks the
        // backend. Sent by the Worker after CatalogManager::get_catalog_schema
        // classified the statement; a Mixed statement's non-MySQL slots are
        // skipped by their node_backend_types entry, as in execute.
        actor_zeta::unique_future<core::result_wrapper_t<ParsedQueryDataPtr>> describe(session_hash_t id,
                                                                                       ParsedQueryDataPtr data);

        using dispatch_traits =
            actor_zeta::dispatch_traits<&MySQLManager::execute, &MySQLManager::discover, &MySQLManager::describe>;

        actor_zeta::behavior_t behavior(actor_zeta::mailbox::message* msg);

        std::pair<bool, actor_zeta::detail::enqueue_result> enqueue_impl(actor_zeta::mailbox::message_ptr msg);

    private:
        std::pmr::memory_resource* resource_;
        // Non-owning: ComponentManager owns it and outlives this actor. This
        // actor is its only driver after startup (execute and discover both run
        // here, serialised by mutex_).
        mysql::ConnectorManager* connector_manager_;
        log_t log_;
        OTX_LOCKABLE_N(std::mutex, mutex_, "MySQLManager::mutex");
        actor_zeta::behavior_t current_behavior_;

        // The statement one slot sends to MySQL — shared by execute (which runs
        // it) and describe (which probes its header), so both see one text.
        core::result_wrapper_t<std::string>
        generate_slot_statement(const components::logical_plan::node_ptr& node,
                                const otterstax::names::resolved_target_t& target,
                                const std::pmr::vector<external_entry_t>& batch,
                                const components::logical_plan::storage_parameters* parameters);
    };
} // namespace db
